### ISSUE TITLE
Null values incorrectly propagated into globals

### ISSUE THREAD

**Issue by patrikbeno** [helm/helm#10167]
[helm-issue.zip](https://github.com/helm/helm/files/7206489/helm-issue.zip)

this is ok:

```
$ helm template qdh chart2/ -f chart2/local2.yaml

# Source: chart2/templates/chart.yaml
app:
  key1: 1
  key2: 2
```

this provides entirely empty map:

```
$ helm template qdh chart2/ -f chart2/local1.yaml

---
# Source: chart2/templates/chart.yaml
app:
  {}
```

when using defaults, only `chart2` defaults are provided to chart2, and only `chart1` defaults are provided to chart1. 
I.e., no merging.

```
$ helm template qdh chart2/

---
# Source: chart2/charts/chart1/templates/subchart.yaml
app:
  key1: null
---
# Source: chart2/templates/chart.yaml
app:
  key2: null
```

Output of `helm version`:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`:
N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by patrikbeno** [comment]
probably related to #9806

**Comment by bacongobbler** [comment]
Can you please test again with Helm 3.7.0? Some issues related to globals were resolved in this release.

**Comment by patrikbeno** [comment]
There is a change between 3.6.3 and 3.7.0, but I wouldn't say it's for the better.

**helm 3.6.3**
```
---
# Source: chart2/charts/chart1/templates/subchart.yaml
app:
  key1: null
---
# Source: chart2/templates/chart.yaml
app:
  key2: null
```

**helm 3.7.0**
```
---
# Source: chart2/charts/chart1/templates/subchart.yaml
app:
  {}
---
# Source: chart2/templates/chart.yaml
app:
  key2: null
```

**Comment by bacongobbler** [comment]
Were you able to determine what may be the cause of this issue?

**Comment by patrikbeno** [comment]
Still an issue, and I don't have the knowledge to track down the cause.
