### ISSUE TITLE
helm delete --purge does not remove helm hook jobs

### ISSUE THREAD

**Issue by maximbaz** [helm/helm#4434]
```
❯ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
                                                                                 
❯ kubectl version                               
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

--------

Create a job with [post-install hook](https://github.com/helm/helm/blob/master/docs/charts_hooks.md) like following:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ipd.fullname" . }}-init-db
  labels:
    app: {{ template "ipd.name" . }}
    chart: {{ template "ipd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - ...
```

Install a release with `helm install`.

Delete the release with `helm delete --purge <releasename>`.

Expected: everything from this release is removed, even completed jobs.

Actual: this hook job is still present:

```
❯ kubectl get all                                
NAME                      READY     STATUS        RESTARTS   AGE
pod/ipd-init-db-djc58     0/1       Completed     0          16m

NAME                    DESIRED   SUCCESSFUL   AGE
job.batch/ipd-init-db   1         1            16m
```

**Comment by bacongobbler** [comment]
Yeah, this is by design.

Any resource that implements a hook is considered "self-managed". Tiller does not manage these at all (other than watching to see that they hit their initial "ready" state). This works well for things like Jobs, Ingress, and things done in post-delete hooks, where there is a good chance that users don't want Tiller to manage the resources.

Because this has been addressed in previous issues like #960, I'm going to go ahead and close this as working as intended.

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/blob/49fc49ecb82a8cd9cbb9d8ba7ce85db2fc355893/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases

**Comment by maximbaz** [comment]
Thanks, I will just use `"helm.sh/hook-delete-policy": hook-succeeded`, that way a failed job still hangs around and yet the successful job is removed immediately.
