### ISSUE TITLE
Helm upgrade with reuse-values, without --set gives YAML error

### ISSUE THREAD

**Issue by timgclark** [helm/helm#4595]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Installed via kubeadm

As previously reported (https://github.com/helm/helm/issues/4337#issuecomment-415603340) #4337 seems to still impact v2.10.0.

`helm upgrade --reuse-values` always seems to fail unless `--set` is also passed to helm with literally *any* key-value:

```
$ helm upgrade percona ./percona-0.5.2.tgz --reuse-values
Error: UPGRADE FAILED: yaml: line 13: could not find expected ':'
$ helm upgrade percona ./percona-0.5.2.tgz --reuse-values --set foo=bar
Release "percona" has been upgraded. Happy Helming!
LAST DEPLOYED: Wed Sep  5 18:17:54 2018
... 
```

**Comment by bacongobbler** [comment]
interesting. I think we fixed this in #4364, but looking at the commit log, it looks like it got missed in the mix and isn't in the 2.10 release. Terribly sorry about that!

Can you try the canary release and see if it's been fixed there? We are closing out on a 2.11 release so we should have a new release out soon. Sorry about that!

https://docs.helm.sh/using_helm/#from-canary-builds

**Comment by timgclark** [comment]
Seeing the same issue with canary:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"37a731db798de00bf94837e207a8a418c76b6557", GitTreeState:"clean"}
...
$ helm upgrade percona ./percona-0.5.2.tgz --reuse-values
Error: UPGRADE FAILED: yaml: line 14: could not find expected ':'
```

**Comment by bacongobbler** [comment]
looks like you're using a v2.10.0 client version though, so that's expected. You'll need to upgrade your client.

**Comment by timgclark** [comment]
Sorry, I thought this was a tiller-side fix.  Still seeing the same with the latest client:

```
ccpuser@kcp:/tmp$ helm version
Client: &version.Version{SemVer:"v2.10+unreleased", GitCommit:"37a731db798de00bf94837e207a8a418c76b6557", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"37a731db798de00bf94837e207a8a418c76b6557", GitTreeState:"clean"}
(reverse-i-search)`q': kubectl describe pod  kubernetes-dashboard-764fcff579-l^Chp|less
ccpuser@kcp:/tmp$ helm upgrade percona ./percona-0.5.2.tgz --reuse-values
Error: UPGRADE FAILED: yaml: line 14: could not find expected ':'
```

**Comment by bacongobbler** [comment]
I was able to reproduce this as well.

```
><> ./helm init --canary-image
><> ./helm version
Client: &version.Version{SemVer:"v2.10+unreleased", GitCommit:"37a731db798de00bf94837e207a8a418c76b6557", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"37a731db798de00bf94837e207a8a418c76b6557", GitTreeState:"clean"}
><> ./helm install stable/wordpress -n wordpress --set foo=bar
NAME:   wordpress
LAST DEPLOYED: Thu Sep  6 12:28:48 2018
NAMESPACE: default
STATUS: DEPLOYED
...
><> ./helm upgrade wordpress stable/wordpress --reuse-values
Error: UPGRADE FAILED: yaml: line 3: could not find expected ':'
```

Seems to work fine with `--reuse-values --set car=star` though. I'll re-open the original issue (#4337) so we can continue to track the issue there. Thanks for the report!
