### ISSUE TITLE
Installing a CRD with Validation containing `maximum`, `minimum` and/or `multipleOf` fails with Helm v2.14.0

### ISSUE THREAD

**Issue by oscar-martin** [helm/helm#5806]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Minikube` and `DigitalOcean`

I have a chart that deploys a CRD and it has `CustomResourceValidation` with fields `Maximum` and `Minimum` set. This was working properly with Helm `v2.13.1` but after upgrading to `v2.14.0` it [fails](https://github.com/kubernetes/apimachinery/blob/kubernetes-1.14.1/pkg/runtime/converter.go#L206) with:

```
Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64
```

The relevant part of the CRD is this:

```yaml
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```

I've been debugging the issue and I've figured out that the problem might come from the way JSON treats numbers during decoding. First of all, the definition of the type [`JSONSchemaProps`](https://github.com/kubernetes/apiextensions-apiserver/blob/kubernetes-1.14.1/pkg/apis/apiextensions/types_jsonschema.go#L20) that models the `CustomResourceValidation` contains these type declarations for `minimum`, `maximum` and `multipleOf`:

```golang
	Maximum              *float64                   `json:"maximum,omitempty" protobuf:"bytes,9,opt,name=maximum"`
	Minimum              *float64                   `json:"minimum,omitempty" protobuf:"bytes,11,opt,name=minimum"`
	MultipleOf           *float64                   `json:"multipleOf,omitempty" protobuf:"bytes,19,opt,name=multipleOf"`
```

So they expect to be of type `*float64`. 

**My guess is**:
New Helm `v2.14.0` implements a new way to wait till the CRD is established. It is using [`Get`](https://github.com/helm/helm/blob/release-2.14/pkg/kube/client.go#L520) for fetching the actual CRD content from Kubernetes. After fetching the CRD data from Kubernetes, it tries to convert this from `Unstructured` format into the actual `apiextv1beta1.CustomResourceDefinition` type [here](https://github.com/helm/helm/blob/release-2.14/pkg/kube/client.go#L526). When the values of any of those fields are integers, it fails as described above. Looking into the conversion code, which resides in Kubernetes [codebase](https://github.com/kubernetes/apimachinery/blob/kubernetes-1.14.1/pkg/runtime/converter.go#L153), it is not handling the possibility of converting from an `int64` value as the source (which is read from the Unstructured representation of the CRD content coming from Kubernetes) into a `float64` as the destination (this is the type declared in the `JSONSchemaProps` aforementioned). I think the problem is in this conversion handling.

I have done some tests to validate my guess:

1. If I use a float value as the value for any of those fields in the CRD, it works (e.g. `10.5`). **But** if a whole number in float format is used (e.g. `10.0`) it does not work. Json decoding will render it as integer.
2. I have edited method [`newCrdWithStatus`](https://github.com/helm/helm/blob/release-2.14/pkg/kube/client_test.go#L529) in `client_test.go` with these content to test it:

```go
func newCrdWithStatus(name string, status apiextv1beta1.CustomResourceDefinitionStatus) apiextv1beta1.CustomResourceDefinition {
	f1 := 1.0
	f2 := 10.0
	crd := apiextv1beta1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: metav1.NamespaceDefault,
		},
		Spec: apiextv1beta1.CustomResourceDefinitionSpec{
			Group: "aGroup",
			Validation: &apiextv1beta1.CustomResourceValidation{
				OpenAPIV3Schema: &apiextv1beta1.JSONSchemaProps{
					Properties: map[string]apiextv1beta1.JSONSchemaProps{
						"replicas": apiextv1beta1.JSONSchemaProps{
							Minimum: &f1,
							Maximum: &f2,
							Type:    "integer",
						},
					},
				},
			},
		},
		Status: status,
	}
	return crd
}
```
With this change, the test `TestWaitUntilCRDEstablished` fails. However, if `f1` and `f2` contain not whole numbers in float format (e.g. `10.2`), it works.

3. I have added the conversion from `int64` to `float64` in [`converter.go`](https://github.com/kubernetes/apimachinery/blob/kubernetes-1.14.1/pkg/runtime/converter.go#L153) and it worked in any case with this change:
```go
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		switch dt.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			dv.Set(sv.Convert(dt))
			return nil
		case reflect.Float32, reflect.Float64:
			dv.Set(sv.Convert(dt))
			return nil
		}
```

**Comment by bacongobbler** [comment]
See #5750.

**Comment by bacongobbler** [comment]
Oh sorry! That's an unrelated issue.

cc'ing @mortent for visibility

**Comment by carlowouters** [comment]
We experience this exact same error when trying to deploy [Kong via the stable helm chart](https://github.com/helm/charts/tree/master/stable/kong).  It worked fine in 2.13.1, but with upgrade to 2.14 the same error appears when the kongplugin custom resource definition is installed (https://github.com/helm/charts/blob/master/stable/kong/templates/crd-kongplugins.yaml).  

Reading @oscar-martin 's explanation, I tried to change the priority values from 1 to 1.1, as those are the only integers visible in the yaml.  However, that didn't work.

**Comment by shamil** [comment]
I'm experiencing exactly same problem with one of the CRDs, is there any workaround found for this problem?

**Comment by oscar-martin** [comment]
We were forced to use an older version of helm (and tiller) due to this.

**Comment by lyndon160** [comment]
Is there any update on this issue?

**Comment by HusterWan** [comment]
also occurred this error on 2.14.3

**Comment by keeganmccallum** [comment]
encountered this one v2.16.1 as well

**Comment by AceHack** [comment]
Any update on fixing this issue in 2.x?

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.

**Comment by joell** [comment]
@bacongobbler: I have confirmed that this bug still occurs in Helm 3.5.1 and appears to do so for the same reasons that @oscar-martin described in his original report.  Though the CRD conversion code in Helm 3.5.1 now appears to be [here](https://github.com/helm/helm/blob/f5ef87b96e791ca9971231699fc5af687f748bae/pkg/kube/wait.go#L123), the underlying issue that `Maximum`  and `Minimum` are defined as `float64` fields in the `JSONSchemaProps` type remains in Kubernetes, [as recent as v0.20.0](https://github.com/kubernetes/apiextensions-apiserver/blob/2297f54428aa4151300668444dfa84a4c234379f/pkg/apis/apiextensions/types_jsonschema.go#L30).

Could you please re-open this bug until the issue has been fixed in Helm 3?

**Comment by bacongobbler** [comment]
I'm not sure what we can do here to resolve this issue. Kubernetes expects a floating point value, but the input was an integer. IMO this seems like a documentation issue or a bug in Kubernetes's schema. But I'll re-open this anyway.

If you have a suggestion on how we can convert the manifest to a CRD value and coerce those values to a float, we'd welcome a PR.

**Comment by BlaineEXE** [comment]
We are having users of Rook report this issue also. I don't necessarily see it as a problem that the schema expects a `*float64` for minimum and maximum. Mathematically speaking, `1` is just a special form of decimal (floating point). I would guess the problem could be solved in the code that parses/interprets the value to allow int forms of number to be read into a float value. I'm not sure where that code lives, however.

**Comment by allen-servedio** [comment]
We are going to test things out, but @BlaineEXE may be right - this was in the K8s 1.20 release notes:

>  K8s.io/apimachinery: runtime.DefaultUnstructuredConverter.FromUnstructured now handles converting integer fields to typed float values (#93250, @liggitt) [SIG API Machinery]

**Comment by markmandel** [comment]
We just updated our CRDs in [Agones](https://agones.dev) to have a much more expansive validation schema (We import PodTemplateSpec for example), and this hits us particularly hard now. Any change in CRD validation schema now requires a full uninstall and reinstall -- and CRD changes now happen each time we switch what K8s platform we support, which is usually arond every 12 week (2 releases).

We're just moving to support 1.18 now. 1.120 is going to be a while away for us. 🙁

(Tried with `--force` ran into other issues with Service accounts)

Happy to test our fixes or anything of the sort, if it helps? can we backport anything from K8s 1.20?

**Comment by allen-servedio** [comment]
Okay, we tested it out and it does appear to be fixed now in 1.20 (at least for our use case) - we used maximum and minimum.

**Comment by bacongobbler** [comment]
Sounds like this has been fixed upstream. Please upgrade to kubernetes 1.20 for the fix. Let us know if you still run into issues. Thanks for finding the fix!

**Comment by markmandel** [comment]
I'd push back on marking this as fixed. Moving to 1.20 isn't an option for many users of Helm.

GKE doesn't yet support 1.20, neither does EKS. Looks like it's just(?) coming to AKS now (I can never quite tell what versions are supported without reading the entire release history). I'd posit that that's a big chunk of the Kubernetes user base.

Also many companies and users are locked to a specific version of Kubernetes for a long time, and I would argue that it's not a simple endeavour to choose a new version and re-deploy their whole stack.

**Comment by bacongobbler** [comment]
Do you have suggestions on how to fix this within Helm itself? We would welcome a PR to help backport a fix for users running older versions of Kubernetes, provided the fix is backwards-compatible.

**Comment by markmandel** [comment]
@bacongobbler - I haven't had a chance to look into the code (and I totally get the request for input/PRs here, and I may end up doing just that, because we rely on Helm as well) -- I'm just arguing that I don't think that the bug can be closed, when the outstanding issue still exists for a large chunk of the user base.

Directions on where in the code the issue is generating from, and any general directions would be useful on this ticket, so as a community we can look into the issue are also appreciated, but I would argue that they are a separate concern from whether the bug should be closed or not.
