### ISSUE TITLE
Helm upgrade failing since 2.12

### ISSUE THREAD

**Issue by rafagonc** [helm/helm#5897]
Helm keeps failing since 2.12 when you add a new resource to an existing chart, it succeeds first time but it fails sequentially after the first `helm upgrade`. On 2.14.1 the error message is prettier but the error continues.

helm upgrade processei processei-1.1.tgz 
Release "processei" has been upgraded.
LAST DEPLOYED: Fri Jun 14 22:15:26 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                DATA  AGE
processei-nginx-ingress-controller  5     137d

==> v1/Deployment
NAME                 READY  UP-TO-DATE  AVAILABLE  AGE
processei-pgbouncer  1/1    1           1          3s

==> v1/PersistentVolume
NAME        CAPACITY  ACCESS MODES  RECLAIM POLICY  STATUS     CLAIM                         STORAGECLASS  REASON  AGE
postgresql  25Gi      RWO           Retain          Bound      default/processei-postgresql  postgresql    137d
rabbitmq    8Gi       RWO           Retain          Available  rabbitmq                      137d

==> v1/PersistentVolumeClaim
NAME                  STATUS  VOLUME      CAPACITY  ACCESS MODES  STORAGECLASS  AGE
processei-postgresql  Bound   postgresql  25Gi      RWO           postgresql    137d

==> v1/Pod(related)
NAME                                                      READY  STATUS   RESTARTS  AGE
processei-captcha-85754bbc88-qswj7                        1/1    Running  6         7d20h
processei-cronos-65f555f99-8dp9r                          1/1    Running  0         3h44m
processei-nginx-ingress-controller-775bc6d4b7-kmmkq       1/1    Running  0         7d19h
processei-nginx-ingress-default-backend-7fb678dbdc-hsjgk  1/1    Running  3         29d
processei-notifications-notifications-f7fbd7b68-lxbr4     1/1    Running  0         3h44m
processei-pgbouncer-689d6cb76d-fpxtz                      2/2    Running  0         2s
processei-postgresql-b449c7f5-dscm7                       2/2    Running  0         3h44m
processei-processei-68bbf8544b-shgzr                      1/1    Running  0         31m
processei-worker-api-8997986d6-5sgf9                      1/1    Running  0         3h44m
processei-worker-api-8997986d6-ln9cd                      1/1    Running  0         3h43m
processei-worker-api-8997986d6-m64jv                      1/1    Running  0         3h44m
rabbitmq-0                                                1/1    Running  7         137d

==> v1/Secret
NAME                  TYPE    DATA  AGE
bounceruri            Opaque  4     3s
processei-postgresql  Opaque  1     137d

==> v1/Service
NAME                                     TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)                                      AGE
db-postgresql                            NodePort   10.97.151.52   <none>       5432:5432/TCP                                137d
pgbouncer-service                        ClusterIP  10.111.112.50  <none>       5432/TCP,9127/TCP                            3s
processei-nginx-ingress-controller       NodePort   10.103.242.63  <none>       80:80/TCP,443:443/TCP                        137d
processei-nginx-ingress-default-backend  NodePort   10.105.27.158  <none>       80:28100/TCP                                 137d
rabbitmq                                 NodePort   10.106.97.9    <none>       5672:5672/TCP,4369:6170/TCP,25672:24324/TCP  137d
rabbitmq-management                      NodePort   10.110.115.81  <none>       15672:31059/TCP                              137d
service-captcha                          NodePort   10.106.40.26   <none>       80:25218/TCP                                 137d
service-cronos                           NodePort   10.110.40.77   <none>       80:28721/TCP                                 137d
service-processei                        NodePort   10.110.77.41   <none>       80:9135/TCP                                  137d

==> v1/ServiceAccount
NAME                     SECRETS  AGE
processei-nginx-ingress  1        137d

==> v1beta1/ClusterRole
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/ClusterRoleBinding
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/Deployment
NAME                                     READY  UP-TO-DATE  AVAILABLE  AGE
processei-captcha                        1/1    1           1          137d
processei-cronos                         1/1    1           1          137d
processei-nginx-ingress-controller       1/1    1           1          137d
processei-nginx-ingress-default-backend  1/1    1           1          137d
processei-notifications-notifications    1/1    1           1          137d
processei-postgresql                     1/1    1           1          137d
processei-processei                      1/1    1           1          137d
processei-worker-api                     3/3    3           3          137d

==> v1beta1/PodDisruptionBudget
NAME                                     MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
processei-nginx-ingress-controller       1              N/A              0                    137d
processei-nginx-ingress-default-backend  1              N/A              0                    137d

==> v1beta1/Role
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/RoleBinding
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/StatefulSet
NAME      READY  AGE
rabbitmq  1/1    137d

root@master:~# helm upgrade processei processei-1.1.tgz 
UPGRADE FAILED
Error: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
root@master:~# helm upgrade processei processei-1.1.tgz  --reuse-values
UPGRADE FAILED
Error: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

Output of `helm version`: Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): self-hosted

**Comment by bacongobbler** [comment]
Have you tried doing what the error suggests? What is the result?

**Comment by karuppiah7890** [comment]
@rafagonc Let me know if I am reiterating the issue correctly

1. you created a chart with some resources
2. installed the chart - release got created
3. added some resources to chart
4. upgraded the release - it worked
5. upgraded again - it failed

is that the case? if yes, I am not able reproduce it with 2.14.1

**Comment by rafagonc** [comment]
I have this problem specially when the chart has subcharts. My chart was installed on helm 2.12 I tried to update with 2.14, I did not want to but I will delete and install a brand new chart on 2.14 and try to update with 2.14.

**Comment by rafagonc** [comment]
When the installation occurs on 2.12 and upgrade on 2.14 it has the same bug, but when I installed using 2.14 the nexts updates was running fine.

**Comment by karuppiah7890** [comment]
That looks like a bug we don't want. I will try to reproduce this. I don't
think people should be deleting and reinstalling to just upgrade from 2.12
to 2.14 and use the new version without any issues

**Comment by rafagonc** [comment]
#3275

**Comment by JasonCarter80** [comment]
I've been getting this constantly on 2.13.1,   just upgraded to 2.14.1 and it seems to have gone away.

**Comment by JasonCarter80** [comment]
And I have it again, deployed everything worked fine, ran the EXACT same deployment, got the error.

**Comment by rafagonc** [comment]
@JasonCarter80 I had to helm delete my chart in the previous versions and install in 2.14, I know sometimes we cannot simply delete in production but it will resolve this issue.

**Comment by JasonCarter80** [comment]
I did that 2 days ago due to a MongoDB subchart and i upgraded to 2.14.2 and still the same.

What i noticed is it didn't start again until my revision count got quite high, so I removed and reinstalled Tiller with MAX_COUNT=10.   

Another thing I've noticed is when i do helm history MYCHART, it throws an grpc error that:

> > helm history attachment-pro
> Error: grpc: trying to send message larger than max (21178680 vs. 20971520)

But when I delete a few of the helm config maps for my chart, both my history, AND the deployment seemed to work.

**Comment by TheNotary** [comment]
I'm experiencing this bug as well.  I just rolled out 2.14 for my org to use, in the hopes I would have more bug fixes than bugs, but apparently I got unlucky this time.  Is anyone able to re-open this issue @rafagonc perhaps?

**Comment by rhefner1** [comment]
I fixed this problem by lowering my Tiller revision counts as @JasonCarter80 stated earlier. Now I can deploy the chart repeatedly without any issues. My guess is that there was some grpc communication issue causing this.

**Comment by karuppiah7890** [comment]
@rhefner1 Could you also post the value of the revision count you already had during the issue? Just in case we need to reproduce the issue, since there are many who have faced the issue

**Comment by karuppiah7890** [comment]
Also, if it's a tiller issue, with Helm 3 it will all go away for good. 😄

**Comment by rhefner1** [comment]
@karuppiah7890 I had 15 and I reduced it down to 3 and once I did a deployment, tiller deleted the old versions and then all subsequent deployments worked.

**Comment by 27Bslash6** [comment]
This problem remains for us even with max revision history at 10.  

Helm version 2.14.3

**Comment by kchekeg** [comment]
This worked for me, but did you try helm rollback? I went all the way back to version 1.
