### ISSUE TITLE
helm3 3.0.0-beta.4 error upgrading PersistentVolumeClaim PVC with no changes

### ISSUE THREAD

**Issue by pmahoney** [helm/helm#6642]
I have a helm chart with a single Deployment and single PersistentVolumeClaim. The Deployment mounts the PVC. My cluster is configured with a default volume provisioner, which does create the PV and adds annotations to the PVC.

With helm 3.0.0-beta.4, I run `upgrade --install` which installs as expected. But if I run the command again, with no changes, I get the following error:

```
$ helm upgrade myrelease /tmp/data/chart --namespace default --logtostderr --install --history-max 3

client.go:385: Cannot patch PersistentVolumeClaim: "mypvc" (PersistentVolumeClaim "mypvc" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims)
client.go:404: Use --force to force recreation of the resource
Error: UPGRADE FAILED: PersistentVolumeClaim "mypvc" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
```

Additionally, if I supply `--force`, helm does delete the PVC (which is **not** desirable) but then fails to re-create it because the resource is still in the process of being deleted (in other words, helm issued the delete command but did not wait for deletion).

Note with helm 3.0.0-alpha.2, I **can** run `upgrade --install` twice in a row with no changes and no errors (as expected).

The PVC after being provisioned
```
kubectl get pvc mypvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: docker-desktop
  creationTimestamp: "2019-10-11T03:29:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/name: mypvc
  name: mypvc
  namespace: default
  resourceVersion: "7770"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/mypvc
  uid: 59fe0916-ebd7-11e9-b99d-0242ac110002
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-59fe0916-ebd7-11e9-b99d-0242ac110002
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  phase: Bound
```

templates/pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    app.kubernetes.io/name: mypvc
spec:
  storageClassName:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
```

templates/deploy.yaml
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app.kubernetes.io/name: mydeploy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeploy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeploy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: default
        persistentVolumeClaim:
          claimName: mypvc
      containers:
      - name: default
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "9999"]
        volumeMounts:
        - name: default
          mountPath: /mypvc
          readOnly: true
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
```
k3s 0.8.0
```

**Comment by karuppiah7890** [comment]
Able to reproduce the issue with the given template yamls

**Comment by bacongobbler** [comment]
This may have to be something to do with how we are generating patchsets between one release and the next now that we are applying a three-way merge patch.

As far as the `--force` flag is concerned, we probably can add the wait logic back in. THat might just be an easy regression to fix.

**Comment by databus23** [comment]
Isn‘t the problem that the `storageclasspath` is set to empty in the tempalte this becomes a problem when k8s fills in a default value and the field is immutable. the three way merge strategy then tried to set the value back to empty.

This can be avoided by omitting empty fields und the template I think.

**Comment by bacongobbler** [comment]
@databus23 excellent catch. That certainly seems like the right assumption here.

I'll do a quick check on my end and confirm that's the case. If that is indeed the root of the issue, then @pmahoney the recommendation would be to remove the empty `storageClassName` field from the template, or to set the `storageClassName` field to whatever Kubernetes changed it to when you invoke `helm upgrade`. That way, when Helm calculates the patchset, it will determine there's no update required for the PVC.

**Comment by bacongobbler** [comment]
Yep. @databus23's suggestion worked. Once the emtpy `storageClassName` field was removed, `helm install/helm upgrade` worked as expected.

**Comment by bacongobbler** [comment]
fixed in #6681.

**Comment by dcherniv** [comment]
@bacongobbler is this fixed in 3.0.2? we are still seeing the problem with 3.0.2

**Comment by hickeyma** [comment]
@dcherniv The fix should be in 3.0.2. Can you raise a new issue explaining the issue you are having?

**Comment by dcherniv** [comment]
@hickeyma https://github.com/helm/helm/issues/7470

**Comment by magick93** [comment]
I'm using v3.6.1 and still have this issue. 

https://github.com/helm/helm/issues/9861
