### ISSUE TITLE
Deleted .helm directory, anyway to restore installed charts

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#7000]
```
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

I deleted `$HOME/.helm` directory and now `helm ls` does not show any of the charts I've installed. Is there a way to restore the installed charts from Tiller? Anyway to restore the charts that are installed in the Kubernetes cluster?

**Comment by rimusz** [comment]
`.helm` does not store chart releases it is only for local Helm CLI to store different data.
simple `helm init --client` should fix it for you.
At least you had TLS CA and etc set how to connect to `tiller`, then you need to restore that too.

**Comment by nodesocket** [comment]
@rimusz getting and error.

```
ubuntu@vpn1:~$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

```
helm init --client
Error: unknown flag: --client
```

**Comment by rimusz** [comment]
sorry my bad it has to be `helm init --client-only`

**Comment by nodesocket** [comment]
Ok, that executed, but still not seeing any of my installed charts.

```
ubuntu@vpn1:~$ helm init --client-only
$HELM_HOME has been configured at /home/ubuntu/.helm.
Not installing Tiller due to 'client-only' flag having been set
ubuntu@vpn1:~$ helm ls
ubuntu@vpn1:~$
```
