### ISSUE TITLE
[Helm 3] improper RBAC setup causes release to be stuck in `pending-install` status despite installing fine

### ISSUE THREAD

**Issue by johnmcollier** [helm/helm#7139]
I tried deploying a simple Go application with a Helm chart using Helm 3, running on Kubernetes. You can find the helm chart [here](https://github.com/johnmcollier/gotemplate). The application installs fine, without error and even reports a status of `deployed`.
```
sh-4.2# helm install gotemplate .
NAME: gotemplate
LAST DEPLOYED: Tue Dec  3 21:36:02 2019
NAMESPACE: che
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

However, it does not show up in the list of releases when I run `helm list`. If I run `helm list --all` it shows up with a status of `pending-install`, despite the install completing fine.
```
sh-4.2# helm list
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
sh-4.2# helm list --all
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
gotemplate      che             1               2019-12-03 21:36:02.653465978 +0000 UTC pending-install gotemplate-0.1.0        1.0     
```

The same Helm chart deploys fine on Helm 2.x.

Output of `helm version`:
```
sh-4.2# helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
sh-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift

**Comment by johnmcollier** [comment]
The debug logs also didn't indicate anything wrong:
```
sh-4.2# helm install gotemplate . --debug
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /tmp/gogotet/gotemplate

client.go:87: [debug] creating 2 resource(s)
NAME: gotemplate
LAST DEPLOYED: Tue Dec  3 21:50:54 2019
NAMESPACE: che
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image:
  pullPolicy: Always
  repository: sample
  tag: v0.1.0
replicaCount: 1
resources:
  cpu: 100m
  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  name: Node
  servicePort: 8000
  type: NodePort

HOOKS:
MANIFEST:
---
# Source: gotemplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cw-gogotet-dccf38f0-160f-11ea-ab26
  labels:
    chart: gotemplate-0.1.0
    projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: codewind-workspace798zbeq2cf3esdnq-6f76c8dbbc
    uid: dce9dd7b-160d-11ea-92b4-00000a1012bc
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
  selector:
    app: gotemplate-selector
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
---
# Source: gotemplate/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cw-gogotet-dccf38f0-160f-11ea-ab26
  labels:
    chart: gotemplate-0.1.0
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
    projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: codewind-workspace798zbeq2cf3esdnq-6f76c8dbbc
    uid: dce9dd7b-160d-11ea-92b4-00000a1012bc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gotemplate-selector
        version: current
        release: cw-gogotet-dccf38f0-160f-11ea-ab26
        projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
    spec:
      containers:
      - name: gotemplate
        image: docker.io/johncollier/cw-gogotet-dccf38f0-160f-11ea-ab26:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        resources: null
        env:
        - name: PORT
          value: "8000"
      serviceAccountName: che-workspace

```

**Comment by johnmcollier** [comment]
Could this be an issue running on Kubernetes? If I deploy the application with Helm 3 on my laptop it's fine, but not if I deploy from within Kubernetes.

**Comment by bacongobbler** [comment]
Hi @johnmcollier. Would you be willing to volunteer your time to improve the error reporting? We'd happily accept PRs to improve this experience for others.

**Comment by galindro** [comment]
@johnhofman @bacongobbler You booth can easily simulate this problem by doing the following:

1 - Try to install any chart, using the --wait flag and the default timeout, with pod resource configuration above the limits of the node to cause the pod to not be scheduled by out of resources (CPU/MEM).
2 - Before helm cmd returns an error to you, just hit Ctrl+C
3 - Now, execute helm list -n <release-namespace> --all

My question now is: work to fix this situation? Any ideas @bacongobbler ?

**Comment by galindro** [comment]
I could workaround it by doing this:

`helm uninstall <my-release> -n <my-release-namespace>`

**Comment by sunnygoel8** [comment]
@johnmcollier @bacongobbler , We are facing exact similar issue while trying to deploy Pega platform on PKS via. Helm. Will try again by adding `update` verb on secrets resource in Role file. 

But wanted to understand why does **Helm v3** needs that to display the release status properly ?

**Comment by bacongobbler** [comment]
Helm stores information about an install/upgrade into a secret. See more: https://helm.sh/docs/topics/architecture/

**Comment by sunnygoel8** [comment]
@bacongobbler  My bad. I read that piece when started working on Helm v3 a few weeks ago.. Thanks for the prompt response..

**Comment by sunnygoel8** [comment]
@bacongobbler , we added the "update" verb to Secrets resource in Role file and applied that to our account as well but still helm release shows **pending-install** status..

**Comment by gtirloni** [comment]
Facing the same issue. Cluster installed with kubeadm 1.18.2 and using helm 3.2.0

```
$ helm list -a
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS         	CHART     	APP VERSION
test	default  	1       	2020-05-04 20:40:09.827303259 +0000 UTC	pending-install	kong-1.1.0	2.0.4
```

**Comment by deepakthaman** [comment]
**Same Issue even after using --wait and timeout flags on helm3**

**The timeout never happens** 

`--wait --timeout 2h`

`# helm3 version --short
v3.2.1+gfe51cd1`


**Chart goes into pending-install no timeouts happening** 
`
# date
Thu May 21 19:33:38 UTC 2020

# helm3 history my-chart -n my_namespace
REVISION        UPDATED                         STATUS          CHART                                           APP VERSION     DESCRIPTION
1               Thu May 21 10:47:19 2020        pending-install my-chart                                        1.0             Initial install underway

# date
Thu May 21 19:33:56 UTC 2020
`

**The chart has a Post-Install Hook which never got started**.

`    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation`

Any ideas where to look for any error logs for hook start issues ?

**Comment by geota** [comment]
Im facing this issue with nginx-ingress chart. All other charts seem to deploy fine. The pods are launched and showin as healthy. 

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

```

**Comment by aude** [comment]
For me, a release ended up with `pending-install` status because an installation through Terraform had an error and aborted.

What I did to fix it (but be sure what you're doing!) was to manually edit the secret `sh.helm.release...` from `status: pending-install` to `status: deployed`. Then I did a re-install/upgrade to try and get it into a known good state.

**Comment by herrberk** [comment]
We are experiencing this issue with Helm 3 as well. Each time we install, all the pods start successfully and the post-install hook (Job) succeeds but once in a while Helm does not complete the `install` command with log: `helm.go:84: [debug] failed post-install: timed out waiting for the condition`. 

Either Helm is not receiving the status of the completed Job from the Kubernetes API or something is wrong in that area.

**Comment by drurenia** [comment]
@bacongobbler, sorry for mentioning you on an old issue. We have been experiencing this problem a lot lately and I was trying to come up with a way Helm can identify it and fix itself. I was thinking about something along the lines:

1. Check if the last release is in a `pending-install` state
2. If it is, get the resource list from that release and check whether the resources were created (something similar with the `waitForResources` (https://github.com/helm/helm/blob/master/pkg/kube/wait.go)
3. If everything was created successfully, then mark the release as `deployed; meaningful error otherwise

Would a PR with such solution be welcome?

**Comment by siavashs** [comment]
We faced and issue with a release getting stuck in `pending-rollback` while all resources were finally stable. This happened since the client was not running any more on our CD system.
Here is how I fixed it without uninstalling the release: https://gist.github.com/siavashs/7e3715879c0e946167749fa9a358380a

**Comment by hezise** [comment]
we're also faces the issue we deployed rook and we got pending-install.
we can't delete the rook and re deploy it, because it means destroying all the kubernetes  cluster

**Comment by artazar** [comment]
I faced a similar issue with nginx-ingress following the [Installation with Helm](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/) guide. It creates a service of LoadBalancer type with default values that, in case there is no cloud provider support, will hang in pending state, causing the Helm release to be stuck:

```
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress-nginx-ingress   LoadBalancer   172.20.214.58   <pending>     80:31907/TCP,443:30199/TCP   6m17s
```

The fix is to pass `controller.service.create=false` value during the chart installation.

Hope this helps someone.

**Comment by sunnygoel8** [comment]
@artazar , Did you install nginx-ingress on k8s cluster that was running locally? And how did you create the cluster - using kubeadm or some other tool ? Reason I ask, because if someone wants to create the k8s cluster from scratch using kubeadm utility On-premise and expose the ingress externally, then what needs to be done ?

**Comment by artazar** [comment]
@sunnygoel8 this is slightly unrelated to the thread. I have the answer for you, normally it is MetalLB https://metallb.universe.tf that helps to do that. But let's please avoid abusing the github issue and discontinue this topic.

**Comment by manast** [comment]
I faced this issue, lack of update verb on secrets, so I ended with a bunch of installed helm charts that are working but that cannot be upgraded with Helm. I tried to manually update the label to "deployed", but helm still believes they are in "pending-install",  I guess there is some other bookkeeping necessary in order for helm to "understand" they are in deployed status. Does anybody know what steps to take so that I can fix these deployments? (deleting them and re-installing them is not really and option for me...).

**Comment by MohammedFadin** [comment]
I have been banging my head on this issue until I realized that my SA does not have the Update verb.

**Comment by locmai** [comment]
> I faced this issue, lack of update verb on secrets, so I ended with a bunch of installed helm charts that are working but that cannot be upgraded with Helm. I tried to manually update the label to "deployed", but helm still believes they are in "pending-install", I guess there is some other bookkeeping necessary in order for helm to "understand" they are in deployed status. Does anybody know what steps to take so that I can fix these deployments? (deleting them and re-installing them is not really and option for me...).

You could try `helm rollback <release-name> <revision>` which the revision is the latest revision (in my case is 1). I fixed this issue with that,

**Comment by nikoul** [comment]
> > I faced this issue, lack of update verb on secrets, so I ended with a bunch of installed helm charts that are working but that cannot be upgraded with Helm. I tried to manually update the label to "deployed", but helm still believes they are in "pending-install", I guess there is some other bookkeeping necessary in order for helm to "understand" they are in deployed status. Does anybody know what steps to take so that I can fix these deployments? (deleting them and re-installing them is not really and option for me...).
> 
> You could try `helm rollback <release-name> <revision>` which the revision is the latest revision (in my case is 1). I fixed this issue with that,

That worked for me. Putting the currently installed version in the helm rollback only updated the status to "deployed", nothing else.

**Comment by transacid** [comment]
I can confirm that adding "update" to "secrets" rbac solved it for me

**Comment by nicksc423** [comment]
I am still running into this issue, adding the update to secrets RBAC has not fixed it for me. I have the ClusterAdmin role so my assumption is its something else...

**Comment by transacid** [comment]
it seems that `patch` is also required

**Comment by bacongobbler** [comment]
Checking in on the status here... Has anyone looked into the work that was done in https://github.com/helm/helm/pull/9180, and the feedback that was provided there? A few community members including myself have chimed in that issue, but that does appear to be the start of a fix.

**Comment by bacongobbler** [comment]
Updated the title to differentiate the discussion between this ticket and #4558.

**Comment by thisisommore** [comment]
Is this fixed, I am still getting this issue

**Comment by uk1988** [comment]
had a similar issues with helm stuck in pending-install 
in my case it was because of 2 cron jobs ...
cron jobs were planed for late night and 2 pvc claims were pending because of it 
however claims where executed until pvc claims happened...
very anoying ...
