### ISSUE TITLE
`Error: rendered manifests contain a resource that already exists` but nothing shows up on `helm list --all`

### ISSUE THREAD

**Issue by saicharanduppati** [helm/helm#7418]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

I'm trying to helm install but helm comes back saying with following error
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: scheduledsparkapplications.sparkoperator.k8s.io`

but when I do `helm list --all`, nothing comes up and therefore I unable to remove any resource to proceed with installation.

Any help appreciated! Thanks!

See the attached screenshot:
![Screen Shot 2020-01-16 at 3 36 00 PM](https://user-images.githubusercontent.com/6623246/72571917-cecb9900-3875-11ea-9387-dd7514265768.png)

**Comment by hickeyma** [comment]
@saicharanduppati It seems like CRD `scheduledsparkapplications.sparkoperator.k8s.io` already exists in your cluster. This is causing the conflict.

BTW,  to get all releases in all namespaces, use `--all-namespaces` flag with `helm ls`.

**Comment by saicharanduppati** [comment]
Thanks for the quick response, @hickeyma 

It makes sense it exists in the cluster, but I don't see anything on `helm ls --all-namespaces`. I think the clue might be in that there is no namespace attached to previous installation. Not sure, how that got through.

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: scheduledsparkapplications.sparkoperator.k8s.io`

![Screenshot from 2020-01-17 10-12-40](https://user-images.githubusercontent.com/6623246/72635559-ece6d700-3911-11ea-80b0-6086a58b6c72.png)

**Comment by hickeyma** [comment]
The CRD could exist because the chart that deployed it, may not remove the CR object from the cluster. In Helm 3, this is expected behaviour as Helm will only install CRDs. 

I just mentioned the `--all-namespaces` flag for your information.

**Comment by boxcee** [comment]
I have the same problem.

Helm: 
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
Command I run:
```
helm install sparkoperator incubator/sparkoperator --namespace sparkoperator --version 0.6.1
```
Error message:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: sparkapplications.sparkoperator.k8s.io
```

I tried removing the CRDs manually as I can not find any chart installed (event with `--all-namespaces`). Does not help. On install I get the same error message again.

**Comment by misterspeedy** [comment]
Same issue here.

Followed the steps in https://docs.microsoft.com/en-us/azure/aks/ingress-basic.

Then deleted the namespace:

    kubectl delete namespace <mynamespace>

Then performed the steps again, got the 'resource that already exists' error at the `helm install nginx-ingress...` step.

If I do

    helm list --all

...I get an empty list.

I'm a beginner at all of these but it seems to me the process should be idempotent.

**Comment by misterspeedy** [comment]
Further to the above

     kubectl get crd

Returns just one item which was created last September and so presumably isn't relevant.

**Comment by misterspeedy** [comment]
Adding `--skip-crds` to the `helm install...` command gives the same error.

**Comment by misterspeedy** [comment]
Tried repeating the first three steps of the tutorial using the original namespace from the tutorial. I.e. ``ingress-basic``. Got the same error, so whatever leaked, it isn't namespaced.

**Comment by ieciura** [comment]
A leftover CRD scheduledsparkapplications.sparkoperator.k8s.io seems to be the cause.
In my case removing the previously created CRD resources did the trick (these are not removed when removing the release).

**Comment by vaishali-prophecy** [comment]
Getting the same error.
helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}

--skip-crds also doesnt help.. Also, is there a way to make this operation idempotent instead of passing different flags each time?

**Comment by talzion12** [comment]
I encountered this problem after deleting the prometheus operator chart which creates many CRDs and other stuff, and apparently doesn't delete them when removed.

I used this to delete everything the chart creates.
I would advise to run this in an empty namespace, so that it will only delete global resources.
Use at your own risk.

```shell
helm template . | \
  yq 'select(.kind != null) | "\\(.kind)/\\(.metadata.name)"' -r | \
  xargs kubectl delete
```

**Comment by sehz** [comment]
same issue.  It started with deleting namespace without uninstalling chart.
After I removed my CRD definitions, I was able to install chart. 
However, if I remove and install chart again, the installation fails again with same message.

I tried both Helm v3.0 and V3.10.  Same problem

**Comment by scbizu** [comment]
`kubectl get all` and delete the reported conflict resource(or all related resources if needed? ) works for me.

**Comment by hickeyma** [comment]
This initial issue opened by @saicharanduppati was resolved in https://github.com/helm/helm/issues/7418#issuecomment-575736342.

Even though symptoms are the same for @boxcee @misterspeedy @vaishali-prophecy @sehz, the main issue is some resource that is in the cluster conflicting with trying to deploy a chart. In this case, if they chart release no longer exists (for whatever reason) and resources are left behind in the cluster, then manually removing them using `kubectl` is the best approach.

This is pretty much the approach used b y @ieciura and @scbizu.

**Comment by hickeyma** [comment]
Going to close this PR because it was resolved for the person who raised it.

If you have issues similar to these symptoms, raise a new issue putting in the details of how it fails for you.

**Comment by miradnanali** [comment]
Solution:


kubectl delete clusterrole nginx-ingress

kubectl delete clusterrolebinding nginx-ingress

**Comment by ktalant** [comment]
check for the clusterrole and clusterrolebinding delete them all, it should solve the problem

kubectl get clusterrole | grep ingress
kubectl get clusterrolebinding | grep ingress 

it did solve in my case.

**Comment by ktalant** [comment]
![image](https://user-images.githubusercontent.com/38672847/77093854-feb42b80-69e1-11ea-81a8-ec2e8f0fc9b3.png)

**Comment by ktalant** [comment]
> same issue. It started with deleting namespace without uninstalling chart.
> After I removed my CRD definitions, I was able to install chart.
> However, if I remove and install chart again, the installation fails again with same message.
> 
> I tried both Helm v3.0 and V3.10. Same problem

![image](https://user-images.githubusercontent.com/38672847/77094036-43d85d80-69e2-11ea-8239-b5945db0fdd3.png)

**Comment by GarbageYard** [comment]
I had a similar issue. I mistakenly used _kubectl_ for removing a deployment although the deployment was initially done using _helm_. Using @scbizu's comment, i ran the following command:

`kubectl.exe -n my-namespace get all`

This showed me that the _svc_ was still not deleted. After deleting it, i again ran the `helm upgrade` command and it worked fine.

**Comment by styk-tv** [comment]
Perfect example is Hashi Vault

Nice chart, works with v3 only:

1) helm3 upgrade --install Something is not right. I want to wipe it. 
2) helm3 list (empty, oh no, f..k)
3) kubectl delete ns vault (but crd's live outside)
4) fix then helm3 upgrade --install (cannot do because not everything got deleted)
5) me angry at helm3 developers, 

what is broken here is fully deployed chart (with some minor storage detail) is still deployed, so why not showing in the list of deployed helm packages so it could not be deleted?

FIX IT PLEASE. This should be reopened.
```version.BuildInfo Version:"v3.1.2"```

**Comment by dwdraju** [comment]
It works on v3.2.0.

**Comment by smaslennikov** [comment]
I was having the same issue running 3.2.0. I finally figured out that my ingress had no name. Pretty embarrassing.

**Comment by Celakanth-VSI** [comment]
I just gave it a new name helm install nginx-ingressdv ingress-nginx/ingress-nginx seemed to work

**Comment by chetanagrawal** [comment]
Just go on deleting the conflicting resources and it should work. In my case I had to delete 3 resources:

  246  kubectl delete rolebinding -n kube-system aws-load-balancer-controller-leader-election-rolebinding
  249  kubectl delete mutatingwebhookconfiguration aws-load-balancer-webhook
  251  kubectl delete validatingwebhookconfiguration aws-load-balancer-webhook

**Comment by maniankara** [comment]
Wondering why there is suggestions and lot of support for deletion of resources 🤔  Atleast I cannot do it straight into my production clusters.. 😃

**Comment by pnutmath** [comment]
`kubectl get CustomResourceDefinition --all-namespaces` works for me to get the CustomResourceDefinition attached to no namespace

**Comment by Yougigun** [comment]
> Solution:
> 
> kubectl delete clusterrole nginx-ingress
> 
> kubectl delete clusterrolebinding nginx-ingress

this works also for some similiar issue. thx a lot.

**Comment by JornShen** [comment]
> 

@shaneutt I face same problems. But I add same label and annotation for my detailed ds and service account, it doesn't work. should I label and annotation for all the resources?

**Comment by er-jagdish** [comment]
for me, its same issue and  helm ls --all-namespaces is not listing the namespace that i am looking.


>> kubectl get namespaces--- for me this was the issue 

>>kubectl delete ns jenkins  ==> deleted the required name space

 you can delete the duplicate one.

**Comment by TorvaldsDB** [comment]
I guess you installed the server by Helm2, and now you are using Helm3.

I did the following scripts, and it works now:

```shell
kubectl delete service -n <namespace> <service-name>
kubectl delete deployment -n <namespace> <deployment-name>
kubectl delete ingress -n <namespace> <ingress-name>
```

**Comment by jribmartins** [comment]
In my case I had some generateName instead of names in metadata:
```
metadata:
  generateName: random-
```
after changing this to name I could install the chart again

**Comment by CharlyPierce** [comment]
In my case add:
`kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission`

> check for the clusterrole and clusterrolebinding delete them all, it should solve the problem
> 
> kubectl get clusterrole | grep ingress kubectl get clusterrolebinding | grep ingress
> 
> it did solve in my case.

**Comment by mb250351** [comment]
> In my case add: `kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission`
> 
you are a Genious and saved my life. thank you.

**Comment by jizago** [comment]
Hi, I had have the same problem with ingress-nginx but I could resolver delete: 

kubectl delete ClusterRole ingress-nginx 
kubectl delete ClusterRoleBinding ingress-nginx
kubectl delete IngressClass nginx
