### ISSUE TITLE
coalesce.go:196: warning: cannot overwrite table with non table for ...beats (map[port:5044 protocol:TCP targetPort:beats])

### ISSUE THREAD

**Issue by WeetA34** [helm/helm#7902]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Docker Desktop macOS
```
Hello,

when i want to delete a default key by using null override as describe in [documentation](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key), i get the following error:
```
coalesce.go:196: warning: cannot overwrite table with non table for beats (map[port:5044 protocol:TCP targetPort:beats])
Error: UPGRADE FAILED: YAML parse error on logstash/templates/service.yaml: error converting YAML to JSON: yaml: line 16: could not find expected ':'
```
excerpt of the [stable/logstash chart default values](https://github.com/helm/charts/blob/master/stable/logstash/values.yaml):
```
service:
  type: ClusterIP
  annotations: {}
  ports:
    beats:
      port: 5044
      targetPort: beats
      protocol: TCP
```

override values:
```
inputs:
  main: |-
    input {
      http {
        request_headers_target_field => "logstash_headers"
      }
    }

outputs:
  main: |-
   output {
     stdout {
       codec => rubydebug {
         metadata => true
       }
     }
   }

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  ports:
    beats: null
    http:
      port: 8080
      targetPort: http
      protocol: TCP
```

I know i can keep service.ports.beats but as i should be able de remove it and i don't need it, i would like to delete it :)

Thank you

**Comment by waveywaves** [comment]
I was able to reproduce your issue with the following command and output.
```
$ helm install logstash stable/logstash --set service.ports.beats=null                                                                     
coalesce.go:196: warning: cannot overwrite table with non table for beats (map[port:5044 protocol:TCP targetPort:beats])                                                           
Error: YAML parse error on logstash/templates/service.yaml: error converting YAML to JSON: yaml: line 16: could not find expected ':'
```

This is definitely a bug as the example given in https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key outlines the same usage and we should be able to be used in the way you are using.

**Comment by WeetA34** [comment]
Hello,
Yep, i also tried this command but i forgot to put it with its result in my message.
Thank you for completing

**Comment by jdolitsky** [comment]
@WeetA34 - can you try to see the result if using `beats: {}` ?

**Comment by WeetA34** [comment]
@jdolitsky 
excerpt of user supplied values
```
service:
  ports:
    beats: {}
    http:
      port: 8080
      protocol: TCP
      targetPort: http
  type: ClusterIP
```

excerpt of computed values
```
service:
  annotations: {}
  ports:
    beats:
      port: 5044
      protocol: TCP
      targetPort: beats
    http:
      port: 8080
      protocol: TCP
      targetPort: http
  type: ClusterIP
```

It merges an empty map with the default service.ports.beats map. So we obtain the default service.ports.beats map.

**Comment by technosophos** [comment]
I believe this is fixed by #7743

**Comment by technosophos** [comment]
This can be re-tested against Helm 3.2.0-rc.1

**Comment by WeetA34** [comment]
Hi @technosophos,
it works fine with 3.2.0-rc.1

**Comment by WeetA34** [comment]
But i still have the following warning i didn't mention. Not sure if it's related.
```
coalesce.go:160: warning: skipped value for filters: Not a table.
```
default value:
```
filters:
  # main: |-
  #   filter {
  #   }
```
user supplied value:
```
filters:
  main: |-
    filter {
      if [headers][request_method] != "POST" {
        drop { }
      }
```

**Comment by technosophos** [comment]
@WeetA34 but the output was correct? That makes sense, because `filters:` (in default values) is equivalent to `filters: null`, which unsets the table. If you do `filters: {}`, I believe that warning would go away.

Essentially, the fix now strongly distinguishes between the null case and the default case (e.g. `foo:` and `foo: ""`. So the number of warnings will go up when `null` tables, strings, ints, etc are provided.

**Comment by WeetA34** [comment]
ok. understood.
Yes, the output is correct.
I saw it's just a warning.
Thank you @technosophos

**Comment by james-mchugh** [comment]
I am running Helm 3.2.0, but I believe that I am experiencing the same issue. My parent chart has a subchart of Filebeat. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

In the Filebeat values.yaml, the following field is defined:
```yaml
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```
In the parent chart values.yaml, I attempt to overwrite this like so:
```yaml
filebeatConfig: {}
```

I have also tried:
```yaml
filebeatConfig: null
```

However, the following template still gets generated:
```yaml
{{- if .Values.filebeatConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}-config
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.filebeatConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
```
Like so:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: "filebeat"
    chart: "filebeat-7.6.2"
    heritage: "Helm"
    release: "filebeat"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~
    
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```
However, I expected the template to not be generated. This is mostly because I assume that the `filebeatConfig` value would now have a truth value of `false` since it was set to a null/empty dict. Is this assumption correct? I am also surprised that it was able to fill out the contents of `filebeat.yml` as I assumed that would also be deleted.

**Comment by james-mchugh** [comment]
Interestingly, using `--set filebeat.filebeatConfig=null` when installing the chart did work. Is this expected behavior? Should `null`s defined in a parent values.yaml not overwrite child values?

**Comment by Xtigyro** [comment]
> 
> 
> Interestingly, using `--set filebeat.filebeatConfig=null` when installing the chart did work. Is this expected behavior? Should `null`s defined in a parent values.yaml not overwrite child values?

+1

**Comment by ktlast** [comment]
+1 

### Env Note
```
# helm version
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

The filebeat came from: `elastic/filebeat`

```
# helm repo list
NAME   	URL
bitnami	https://charts.bitnami.com/bitnami
elastic	https://helm.elastic.co
```

### Problem:
- Can't overwrite `values` via yaml file: `-f ./my_values.yml` during installing nor upgrading. (Check by `kubectl describe pod`)
- It only works with `--set`; but it is hard to assign all filebeat.yml into a single value for `--set`; I tried, and error messsages took me here.
