### ISSUE TITLE
Unable to get an update from the chart repository: tag explicitly required (OCI ACR chart dependency)

### ISSUE THREAD

**Issue by chuanm** [helm/helm#9738]
Output of `helm version`: 

`version.BuildInfo{Version:"v3.6.0-rc.1", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}`

Output of `kubectl version`: 
```

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS using OCI for repositories

I'm having issues including an OCI ACR as a chart dependency as follows:

```
apiVersion: v2
name: test-operator
description: test-operator
version: 0.0.1

dependencies:
- name: dependency-chart
  version: "0.5.4"
  repository: "oci://someaddresshere.azurecr.io/helm"

```

I'm getting back the following error when I run `helm dep up` on the chart to download the dependency:

```

Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://someaddresshere.azurecr.io/helm/" chart repository:
        tag explicitly required
```

Not quite sure what is going on here, since doing a `helm chart pull` for the corresponding repo as follows works just fine:

`helm chart pull someaddresshere.azurecr.io/helm/dependency-chart:0.5.4`

I'm adhering to the following piece of documentation: [https://helm.sh/docs/topics/registries/#specifying-dependencies](https://helm.sh/docs/topics/registries/#specifying-dependencies), so I'm not sure why this doesn't work

EDIT: So my inability to download the dependencies ended up being the result of something else, but I still get the "tag explicitly required" error, is this some sort of bug?

**Comment by jdolitsky** [comment]
Potentially fixed by https://github.com/helm/helm/pull/9539

**Comment by bacongobbler** [comment]
ping. @chuanm can you confirm whether #9539 resolves your issue?

**Comment by Yop-La** [comment]
I'm getting the same issue with that helm version;

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

**Comment by Yop-La** [comment]
I found a way to solve the problem. Before, I was using a tag like this: gt.v1 and it didn't work. With this tag: v1, it works! :D :D

**Comment by Yop-La** [comment]
But I'm still getting errors in logs:
![image](https://user-images.githubusercontent.com/10812063/123264828-b1830b80-d4fa-11eb-8229-5118a8d22832.png)

Despite the errors, the charts are well downloaded
